### ISSUE TITLE
HttpErrorResponse on Successful signUp

### ISSUE THREAD

**Issue by laslorma** [mraible/ionic-jhipster-example#2]
Hi, first of all thank you very much for this project, it helped me a lot in understanding how to set my ionic / jhipster implementation! =) 

I just want to report that in the signup, I was getting an HttpErrorResponse even when the registration in the jhipster backend was successful. I manage to fixed it by setting the following headers in the post request

```
 /**
   * Send a POST request to our signup endpoint with the data
   * the user entered on the form.
   */
  signup(accountInfo: any) {
    return this.api.post('register', accountInfo, {
      headers: new HttpHeaders().set('Content-Type', 'application/json'),
      responseType: 'text'
    }).share();
  }

````

I would like to contribute but I'm not sure how I should do it?

**Comment by mraible** [comment]
Thanks for this bug report! You should be able to fork this repo, create a branch with your fix, and push it to your repo. GitHub will them prompt you to create a pull request. Then I can review and merge. 🍻

**Comment by mraible** [comment]
Fixed! Thanks for your contribution @laslorma!!
