### ISSUE TITLE
Http 401 UnauthorizedEntryPoint   when accessing a rest in jhipster backend 

### ISSUE THREAD

**Issue by laslorma** [mraible/ionic-jhipster-example#4]
Hello! me again =)
I am getting Unauthorized 401 error when trying to get some info from my backend.
I copied and pasted the jhipster services into the ionic project, but I still don't understand why the auth.interceptor is not setting the authorization header as it should when I use this services, but it works perfectly when I use the services in api.ts.

I'm missing something, but what?

**Comment by mraible** [comment]
Make sure you use `HttpClient` instead of `Http` in your service. [auth-interceptor.ts](https://github.com/mraible/ionic-jhipster-example/blob/master/ionic-jhipster-example/src/providers/auth/auth-interceptor.ts) only works for `HttpClient`.

**Comment by laslorma** [comment]
that did the trick, thank you!
I'll close this ticket now.

**Comment by ernesto-butto** [comment]
A question for @mraible . Why does it works only for `HttpClient`? Why doesn't work with `Http` like it's generated on the Jhipster services ? it would make it easier to reuse the services generated by jhipster on the mobile app.

**Comment by mraible** [comment]
Http is deprecated in Angular 5, and JHipster is upgrading soon. I'm just a bit ahead of the curve. ;)
